<!-- eslint-disable no-console -->
<!-- eslint-disable no-console -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Async Await</title>
  <link rel="stylesheet" href="../../base.css">
</head>
<body>
    
  <script>
    function wait(ms = 0) {
      return new Promise((resolve) => {
        setTimeout(resolve, ms);
      });
    }

    /// /////////////////////////
    // Making a Pizza Dinner
    function makePizza(toppings = []) {
      return new Promise((resolve, reject) => {
        // reject order if they ask for Pawnappul
        if (toppings.includes('Pineapple')) {
          // eslint-disable-next-line prefer-promise-reject-errors
          reject(`You are not getting any üçï because you asked for: ${toppings.join(', ')}`);
        }
        const bakeTime = 500 + toppings.length * 200;
        // cook the pizza for 1s
        setTimeout(() => {
          // when ready resolve
          resolve(`Here is üçï with toppings: ${toppings.join(', ')}`);
        }, bakeTime);
        // when fails reject
      });
    }

    // // Try and Catch

    // Method 1 async function go() {
    //   try {
    //     const pizza = await makePizza(['Pineapple']);
    //   } catch (err) {
    //     console.log(err);
    //   }
    // }
    
    // // Method 2 catch() function with error handler function
    
    // function handleError(err) {
    //   console.log('Does not compute!!!');
    //   console.log(err);
    // }
    // async function go() {
    //   const pizza = await makePizza(['Pineapple']);
    //   console.log(pizza);
    //   return pizza;
    // }
    
    // go().catch(handleError);
    
    // // async functions return a promise
    // // put the result in a variable to use the promise
    // const result = go().catch(handleError);
    // console.log(result);

    // Method 3 Use a makeSafe function

    function handleError(err) {
      console.log('Does not compute!!!');
      console.log(err);
    }

    async function go() {
      const pizza = await makePizza(['Pineapple']);
      console.log(pizza);
      return pizza;
    }

    // // catch it at run time
    // go().catch(handleError);
    
    // or make a safe function with a higher order function HOF
    function makeSafe(fn, errorHandler) {
      return function () {
        fn().catch(errorHandler);
      };
    }

    // go(); // unsafe
    const safeGo = makeSafe(go, handleError);
    safeGo(); // safe
</script>  
</body>
</html>